### PR TITLE
Fix for issue #107

### LINKED ISSUE #107: main.cc is attempting to parse cpu_gpu_mem_copy as kernel_launch
https://github.com/accel-sim/accel-sim-framework/blob/17f819fb49ac3213a1366ae42ec21ef2d4d3c148/gpu-simulator/main.cc#L82-L100

When concurrent kernel is enabled, this piece of implementation will attempt to parse as many lines in   kernelslist.g  as possible, assuming all of which are of command_type==kernel_launch. But when there are cpu_gpu_mem_copy commands after kernel_launch in kernelslist.g, this can cause the simulator to break at trace_parser.cc:282. 
For example consider the kernelslist.g file of backprob-rodinia-2.0-ft:

```
MemcpyHtoD,0x00007fa371500000,16388
MemcpyHtoD,0x00007fa371504400,278596
kernel-1.traceg
MemcpyHtoD,0x00007fa37154c600,68
MemcpyHtoD,0x00007fa37154c800,278596
MemcpyHtoD,0x00007fa371504400,278596
kernel-2.traceg
```

The simulator will fail while parsing the 4th line.

### PR DESCRIPTION
**Pull request by FJShen**
A fix for #107. Intended to be temporary; should be overhauled once asynchronous memcpy is included in the traces

### CODE REVIEW

File: gpu-simulator/main.cc [hunk 1]
```diff
@@ -81,41 +81,41 @@ int main(int argc, const char **argv) {
...
+          stream_busy = true;
+      }
+      if (!stream_busy && m_gpgpu_sim->can_start_kernel() && !k->was_launched()) {
+        std::cout << "launching kernel name: " << k->get_name() << " uid: " << k->get_uid() << std::endl;
+        m_gpgpu_sim->launch(k);
+        k->set_launched();
+        busy_streams.push_back(k->get_cuda_stream_id());
       }
     }
-    else if (kernels_info.empty())
```
Comment (barnes88) [inline gpu-simulator/main.cc:117]: I don't think you should remove the check for bad commands in the kernelslist.g file

File: gpu-simulator/main.cc [hunk 2]
```diff
@@ -81,41 +81,41 @@ int main(int argc, const char **argv) {
...
-      i++;
-      continue;
-    } else if (commandlist[i].m_type == command_type::kernel_launch) {
-      // Read trace header info for window_size number of kernels
-      while (kernels_info.size() < window_size && i < commandlist.size()) {
-        kernel_trace_t* kernel_trace_info = tracer.parse_kernel_info(commandlist[i].command_string);
-        kernel_info = create_kernel_info(kernel_trace_info, m_gpgpu_context, &tconfig, &tracer);
-        kernels_info.push_back(kernel_info);
-        std::cout << "Header info loaded for kernel command : " << commandlist[i].command_string << std::endl;
+    //gulp up as many commands as possible - either cpu_gpu_mem_copy
```
Comment (barnes88) [inline gpu-simulator/main.cc:84]: I think you can remove these 3 lines of comments, it's implied by the loop bounds and isn't really accurate since we don't pop commands off the command list so it never empties and kernels_info will never exceed the window_size

**Review by barnes88 — CHANGES_REQUESTED** [review]

File: gpu-simulator/main.cc (hunk 1 above)
Comment (FJShen) [reply gpu-simulator/main.cc:117]: I agree. It's unwise to not check for bad commands, but the condition would need to be changed - no longer be "kernels_info.empty()", but something more like a "default" case i.e. if "commandlist[i].m_type" is neither kernel_launch nor cpu_gpu_mem_copy, then panic. 
Here's my understanding of why the condition for panicking used to be` if(kernels_info.empty())` - if we enter the outermost while loop with an empty `kernels_info`, and we reach the line `else if (kernels_info.empty())`, it implies `commandlist[i]` was a non-supported command type, so we should panic for undefined command. But that was not sufficient to catch all non-supported commands yet. What if we enter the outermost while loop with `kernels_info` not empty and fails to match the case for both `kernel_launch` and `cpu_gpu_mem_copy`, then the old code would not panic and quietly carry on executing.  
I added the code to check for unsupported command as a else{} statement, does that look better?

File: gpu-simulator/main.cc (hunk 2 above)
Comment (FJShen) [reply gpu-simulator/main.cc:84]: I refined my wording to reflect what you are bothered about - yes, `commandlist` never empties, instead we read it element by element.
I think this comment is not only an explanation of what the loop bounds mean, but rather what this chunk of code is doing, so why not keep it for the convenience of others provided the description is accurate? 
By the way I don't understand why kernels_info.size never exceeds the window size.

Comment (barnes88) [reply gpu-simulator/main.cc:84]: The max length of kernelslist is window_size `(kernels_info.size() < window_size)`, so it never exceeds it.

File: gpu-simulator/main.cc (hunk 1 above)
Comment (barnes88) [reply gpu-simulator/main.cc:117]: looks good

File: gpu-simulator/main.cc (hunk 2 above)
Comment (FJShen) [reply gpu-simulator/main.cc:84]: Good catch, I should have used "reached the window_size" instead of "exceeded"

**Review by barnes88 — APPROVED** [review]
